services:
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
      python manage.py ensure_admin_user &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules

volumes:
  frontend-node-modules: